### ISSUE TITLE
On first start no login screen 

### ISSUE THREAD

**Issue by kinjar1988** [SpreadiesInSpace/cinnamon-dotfiles#1]
Hi SpreadiesInSpace,

I installed your cinnamon dots in endevouros with cinnamon desktop. It's installed successful and everything works perfect but when pc shutdown and start there is no login screen. PC is start automatically.  I mean on fresh start no login screen after that logout and restart works perfect.

Is there any mistake I have done on installing ?

**Comment by SpreadiesInSpace** [comment]
https://wiki.archlinux.org/title/LightDM#Enabling_autologin

If you don't want to manually edit lightdm.conf, you can install lightdm-settings, for slick-greeter or lightdm-gtk-greeter-serttings if you're using the LightDM GTK Greeter.

I haven't made a proper README so I didn't expect people to already be running my scripts in full. In the scripts, I set up autologin for personal ease of use.

I encourage you to look at the cinnamon-dotfiles/home/Setup-Arch.sh script to see what other things I did that might not suit you and comment them out before running.

**Comment by SpreadiesInSpace** [comment]
https://wiki.archlinux.org/title/LightDM#Enabling_autologin

I encourage you to look through both Setup-Arch-Full.sh and Setup-Arch.sh (located in cinnamon-dotfiles/home) and comment out whatever things you don't want before running the scripts, since these are for my personal use. That's why there is no proper README yet.
